name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup SSH agent with your private key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      # Step 3: Run commands on EC2
      - name: Run deploy script on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "
            echo '🚀 Starting deployment on EC2...'
            bash /home/deploy/deploy.sh
            echo '✅ Deployment completed!'
          "
