name: Deploy to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          user: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            echo "🚀 Starting deployment on EC2..."
            chmod +x /home/deploy/deploy.sh
            /bin/bash /home/deploy/deploy.sh
            echo "✅ Deployment completed!"

